/*
//****************DESCRIPTION TABLE******************************
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.description
	(
	id int NOT NULL IDENTITY (1, 1),
	description nvarchar(1000) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.description SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
//************************************** LOG TABLE***************************************************
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.[Log]
	(
	id int NOT NULL IDENTITY (1, 1),
	idUsuario int NOT NULL,
	idMachine int NOT NULL,
	time date NOT NULL,
	status int NOT NULL,
	idDescription int NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.[Log] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT



///////////*******************************OPERATES TABLE*********************************/////////////
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.operate
	(
	idUser int NOT NULL,
	idMachine int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.operate SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


/////////*****************************************USER TABLE
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.[USER]
	(
	id int NOT NULL IDENTITY (1, 1),
	username nchar(20) NOT NULL,
	password nchar(10) NOT NULL,
	type nchar(10) NOT NULL,
	status char(2) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE  dbo.[USER] ADD CONSTRAINT
	PK_Table_1 PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE  dbo.[USER] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

///***********************FINAL ATTACHMENTS
BEGIN TRANSACTION
GO
ALTER TABLE dbo.machine ADD
	status char(2) 
GO
COMMIT
/// MORE*/



/*****after updates ***
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.org
	(
	id int NOT NULL IDENTITY (1, 1),
	name nvarchar(50) NOT NULL,
	datecreated date NOT NULL,
	status nvarchar(10) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.org SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.loc
	(
	id int NOT NULL IDENTITY (1, 1),
	name nvarchar(50) NOT NULL,
	country nvarchar(50) NOT NULL,
	orgID int NOT NULL,
	status nvarchar(10) NOT NULL,
	datecreated date NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.loc SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.role
	(
	id int NOT NULL IDENTITY (1, 1),
	name nvarchar(50) NOT NULL,
	type nvarchar(50) NOT NULL,
	status nchar(10) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.role SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.user_loc
	(
	idUser int NOT NULL,
	idLoc int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.user_loc SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.user_role
	(
	idUser int NOT NULL,
	idRole int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.user_role SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.machine ADD
	idLoc int NULL
GO
ALTER TABLE dbo.machine SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
*/


/*

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.user_machine
	(
	userID int NOT NULL,
	machineID int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.user_machine SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
*/